export const assets = {
  logo: "/assets/logo.svg",
  logoDark: "/logo-dark.svg",
  logoLight: "/logo-light.svg",
  favicon: "/fav.svg",
  menu: "/assets/menu.svg",
  hero: "/assets/hero.jpg",
  heroVideo: "/video/herobg.mp4",
  about: "/assets/about-fleet-hd.jpg",
  aboutPage: {
    founder1: "/assets/about/founder-1.png",
    founder2: "/assets/about/founder-2.png",
    mosaic1: "/assets/about/mosaic-1-hd.jpg",
    mosaic2: "/assets/about/mosaic-2-hd.jpg",
    teamBg: "/assets/about/team-bg-hd.jpg",
    heads: [
      "/assets/about/head-1.png",
      "/assets/about/head-2.png",
      "/assets/about/head-3.png",
      "/assets/about/head-4.png",
    ],
  } as const,
  process: "/assets/about-fleet-hd.jpg",
  processSteps: [
    "/assets/process/step-1-book-hq.jpg",
    "/assets/process/step-2-pickup-hq.jpg",
    "/assets/process/step-3-transport-hq.jpg",
    "/assets/process/step-4-deliver-hq.jpg",
  ] as const,
  cta: "/assets/cta.jpg",
  ctaVideo: "/video/cta-traffic.mp4",
  services: [
    "/assets/services-page/dedicated-transport-hd.jpg",
    "/assets/services-page/truck-carrier-18m-hd.jpg",
    "/assets/services-page/door-delivery-hd.jpg",
    "/assets/services-page/express-transit-hd.jpg",
  ] as const,
  partners: [
    "/assets/partner-1.svg",
    "/assets/partner-2.svg",
    "/assets/partner-3.svg",
    "/assets/partner-4.svg",
    "/assets/partner-5.svg",
    "/assets/partner-6.svg",
    "/assets/partner-7.svg",
  ] as const,
  testimonials: [
    "/assets/testimonial-logo-1.svg",
    "/assets/testimonial-logo-2.svg",
    "/assets/testimonial-logo-3.svg",
    "/assets/testimonial-logo-4.svg",
  ] as const,
  icons: {
    mail: "/assets/icon-mail.svg",
    phone: "/assets/icon-phone.svg",
    external: "/assets/icon-external.svg",
    arrowUp: "/assets/icon-arrow-up.svg",
  },
} as const;
